// Generated by tools/tokens/build.mjs from tokens.css — do not edit.
// The token list (tokens.css `@theme inline`) is the source; edit it there and run `node tools/tokens/build.mjs`.

/** Color utilities (bg-*, text-*, border-*…) by name: `--color-<name>`. */
export const COLOR_TOKENS = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'border',
  'input',
  'ring',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
  'sidebar',
  'sidebar-foreground',
  'sidebar-primary',
  'sidebar-primary-foreground',
  'sidebar-accent',
  'sidebar-accent-foreground',
  'sidebar-border',
  'sidebar-ring',
  'success',
  'warning',
  'tertiary-foreground',
  'secondary-strong',
  'overlay',
  'bar',
  'sticky',
  'handle',
  'link',
  'code',
  'code-foreground',
] as const;

/** Font-size utilities (text-*): `--text-<name>`. Size only — no line-height. */
export const TEXT_TOKENS = [
  'caption2',
  'caption',
  'footnote',
  'detail',
  'subhead',
  'callout',
  'body',
  'title',
] as const;

/** Radius utilities (rounded-*): `--radius-<name>`, all derived from the `--radius` variable. */
export const RADIUS_TOKENS = [
  'ctl',
  'panel',
  'card',
  'sheet',
] as const;

/** Shadow utilities (shadow-*): `--shadow-<name>`. */
export const SHADOW_TOKENS = [
  'hairline',
  'hairline-t',
  'hairline-b',
] as const;

/** Spacing utilities (h-*, min-h-*, size-*…) added by BL UI: `--spacing-<name>`. */
export const SPACING_TOKENS = [
  'toolbar',
  'row',
] as const;

/** Font-family utilities (font-*): `--font-<name>`. */
export const FONT_TOKENS = [
  'sans',
  'mono',
] as const;

/** The CSS variables a theme (or a `ThemeScope`'s `vars`) sets, without the leading `--`. */
export const THEME_VARS = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'border',
  'input',
  'ring',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
  'sidebar',
  'sidebar-foreground',
  'sidebar-primary',
  'sidebar-primary-foreground',
  'sidebar-accent',
  'sidebar-accent-foreground',
  'sidebar-border',
  'sidebar-ring',
  'success',
  'warning',
  'tertiary-foreground',
  'secondary-strong',
  'overlay',
  'bar',
  'sticky',
  'handle',
  'link',
  'code',
  'code-foreground',
  'radius',
  'font-sans',
  'font-mono',
] as const;

export type ThemeVar = (typeof THEME_VARS)[number];
