// Generated by tools/registry/build.mjs from adaptive-pane.json — do not edit.
// AdaptivePane: One pane presented as a column, sheet or pushed page depending on the room it has.
export { AdaptivePane } from '@brett_lamy/ui';
export type { AdaptivePaneMode, AdaptivePaneProps } from '@brett_lamy/ui';
