// Generated by tools/registry/build.mjs from artifact-chat-container.json — do not edit.
// ArtifactChatContainer: Chat docked beside an artifact when wide; a floating glass Composer over the artifact when narrow.
export { ArtifactChatContainer, useArtifactChatContainer, WorkbenchTheme } from '@brett_lamy/ui';
export type {
  ArtifactChatContainerContextValue,
  ArtifactChatContainerProps,
  ArtifactChatContainerSlotChildren,
  WorkbenchThemeProps,
} from '@brett_lamy/ui';
