// Generated by tools/registry/build.mjs from chat-shell.json — do not edit.
// ChatShell: A team-chat scaffold: workspace rail and channels beside the conversation, one drawer when narrow.
export { ChatShell, useChatShell } from '@brett_lamy/ui';
export type { ChatShellContextValue, ChatShellProps, ChatShellSlotChildren } from '@brett_lamy/ui';
