// Generated by tools/registry/build.mjs from chat-shell.json — do not edit.
// ChatShell: A team-chat scaffold: an optional workspace rail and channel sidebar beside the conversation, one drawer when narrow.
export {
  ChatShell,
  ChatShellNav,
  ChatShellNavTrigger,
  ChatShellSidebar,
  ChatShellMain,
  ChatShellHeader,
  ChatShellHeaderIcon,
  ChatShellTitle,
  ChatShellDescription,
  ChatShellHeaderActions,
  chatShellHeaderActionVariants,
  ChatShellHeaderAction,
  ChatShellBack,
  ChatShellFooter,
  ChatShellAside,
  ChatShellPanel,
  useChatShell,
  useOptionalChatShell,
} from '@brett_lamy/ui';
export type {
  ChatShellAsideProps,
  ChatShellBackProps,
  ChatShellContextValue,
  ChatShellHeaderActionProps,
  ChatShellNavProps,
  ChatShellNavTriggerProps,
  ChatShellPanelProps,
  ChatShellProps,
} from '@brett_lamy/ui';
