// Generated by tools/registry/build.mjs from credenza.json — do not edit.
// Credenza: A dialog on wide screens and a draggable tray on phones, from one composition.
export { Credenza } from '@brett_lamy/ui';
export type { CredenzaProps } from '@brett_lamy/ui';
