// Generated by tools/registry/build.mjs from edge-drawer.json — do not edit.
// EdgeDrawer: A drawer that follows the finger from any edge, with rubber-banding and velocity-aware snapping.
export { EdgeDrawer } from '@brett_lamy/ui';
export type { EdgeDrawerProps } from '@brett_lamy/ui';
