// Generated by tools/registry/build.mjs from floating-sheet.json — do not edit.
// FloatingSheet: A floating card that grows into the full page along one drag, over a map or canvas.
export { FloatingSheet, useFloatingSheet } from '@brett_lamy/ui';
export type {
  FloatingSheetAppearance,
  FloatingSheetContextValue,
  FloatingSheetFabPosition,
  FloatingSheetProps,
  FloatingSheetTone,
} from '@brett_lamy/ui';
