// Generated by tools/registry/build.mjs from haptics.json — do not edit.
// Haptics: Named haptic feedback for touch devices, with an on-screen indicator for desktop.
export { Haptics, PAT, HapticIndicator } from '@brett_lamy/ui';
export type { HapticIndicatorProps } from '@brett_lamy/ui';
