// Generated by tools/registry/build.mjs from icon.json — do not edit.
// Icons: An SF Symbols-style icon set on a 24px grid: round-capped strokes in six weights, filled variants, and custom shapes.
export {
  Icon,
  IC,
  ICON_NAMES,
  ICON_ALIASES,
  ICON_CATEGORIES,
  ICON_KEYWORDS,
  ICON_WEIGHTS,
} from '@brett_lamy/ui';
export type {
  IconCanonicalName,
  IconCategory,
  IconName,
  IconProps,
  IconShape,
  IconWeight,
} from '@brett_lamy/ui';
