// Generated by tools/registry/build.mjs from markdown-view.json — do not edit.
// MarkdownView: Docstream-rendered GitBook-flavored Markdown: headings, hints, tables, tabs, highlighted code.
export { MarkdownView, HlPre, DocstreamRefContext } from '@brett_lamy/ui';
export type { DocstreamRefContextValue, MarkdownViewProps } from '@brett_lamy/ui';
