// Generated by tools/registry/build.mjs from message-scroller.json — do not edit.
// MessageScroller: A chat transcript scroller anchored to the newest message, with streaming-aware autoscroll.
export { MessageScroller, WorkbenchTheme } from '@brett_lamy/ui';
export type { MessageScrollerItem, MessageScrollerProps, WorkbenchThemeProps } from '@brett_lamy/ui';
