// Generated by tools/registry/build.mjs from morph.json — do not edit.
// Morph: Shared-element transitions: one element springs between two layouts (mini player → full player), drag-to-dismiss friendly, reduced-motion aware.
export { MorphGroup, Morph, MorphPresence, useMorphTransition } from '@brett_lamy/ui';
export type { MorphGroupProps, MorphPresenceProps, MorphProps } from '@brett_lamy/ui';
