// Generated by tools/registry/build.mjs from motion.json — do not edit.
// Motion: Springs and the motion vocabulary: TextMorph, NumberMorph, IconSwap, Chevron, AnimatedHeight, ContentSwap, Celebrate.
export {
  springs,
  springCss,
  fades,
  useMotion,
  useReducedMotion,
  useSpringTransition,
  TextMorph,
  NumberMorph,
  IconSwap,
  Chevron,
  AnimatedHeight,
  ContentSwap,
  Celebrate,
} from '@brett_lamy/ui';
export type {
  AnimatedHeightProps,
  CelebrateProps,
  ChevronDirection,
  ChevronProps,
  ContentSwapProps,
  IconSwapProps,
  NumberMorphProps,
  TextMorphProps,
} from '@brett_lamy/ui';
