// Generated by tools/registry/build.mjs from navigation-stack.json — do not edit.
// NavigationStack: A controlled push/pop stack with large titles and edge-swipe back.
export { NavigationStack, ScreenWrap } from '@brett_lamy/ui';
export type { NavigationStackProps, Screen, ScreenWrapProps } from '@brett_lamy/ui';
