// Generated by tools/registry/build.mjs from now-playing-bars.json — do not edit.
// NowPlayingBars: The animated equaliser beside the track that's playing — still when paused and under reduced motion — plus the Slider tones for media controls.
export { NowPlayingBars, Slider, SliderTrack, SliderThumb } from '@brett_lamy/ui';
export type { NowPlayingBarsProps, SliderProps, SliderTone } from '@brett_lamy/ui';
