// Generated by tools/registry/build.mjs from progress-ring.json — do not edit.
// ProgressRing: Circular progress: a determinate ring that springs to each value with a rolling percentage, and a CountdownRing that drains second by second and turns red near the end.
export { ProgressRing, CountdownRing, useCountdown } from '@brett_lamy/ui';
export type { CountdownRingProps, ProgressRingProps, ProgressRingTone } from '@brett_lamy/ui';
