// Generated by tools/registry/build.mjs from replay-preview.json — do not edit.
// ReplayPreview: An rrweb session replay in a browser frame: a URL bar that follows the recording, play/pause, a scrubber with click, error, failed-request and navigation markers, speed, fullscreen, a drawn cursor with click ripples, and a skeleton poster while the player loads.
export {
  ReplayPreview,
  formatReplayTime,
  getReplayMarkers,
  getReplayMeta,
  getReplayPointerTrack,
  replayPointerAt,
} from '@brett_lamy/ui';
export type {
  ReplayEvent,
  ReplayMarker,
  ReplayMarkerKind,
  ReplayMeta,
  ReplayPointerTrack,
  ReplayPreviewHandle,
  ReplayPreviewProps,
} from '@brett_lamy/ui';
