// Generated by tools/registry/build.mjs from sidebar.json — do not edit.
// Sidebar: Docked, rail, floating or overlay navigation with workspace, search, sections and items.
export {
  Sidebar,
  SidebarProvider,
  SidebarHeader,
  SidebarContent,
  SidebarFooter,
  SidebarWorkspace,
  SidebarSearch,
  SidebarSection,
  SidebarItem,
  SidebarTrigger,
  SidebarInset,
  SidebarNav,
  useSidebar,
} from '@brett_lamy/ui';
export type {
  SidebarContextValue,
  SidebarItemProps,
  SidebarNavProps,
  SidebarProps,
  SidebarProviderProps,
  SidebarSearchProps,
  SidebarSectionProps,
  SidebarVariant,
  SidebarWorkspaceProps,
} from '@brett_lamy/ui';
