// Generated by tools/registry/build.mjs from side-drawer.json — do not edit.
// SideDrawer: An inspector column: docked beside the content, or an overlay sheet with a scrim.
export { SideDrawer } from '@brett_lamy/ui';
export type { SideDrawerProps } from '@brett_lamy/ui';
