// Generated by tools/registry/build.mjs from skeleton.json — do not edit.
// Skeleton: Loading placeholders with a soft left-to-right sweep instead of a pulse: text lines, circles, rects and rounded blocks, and a SkeletonText paragraph with a shorter last line.
export { Skeleton, SkeletonText, skeletonVariants } from '@brett_lamy/ui';
export type { SkeletonProps, SkeletonTextProps } from '@brett_lamy/ui';
