// Generated by tools/registry/build.mjs from split-view.json — do not edit.
// SplitView: An adaptive sidebar / supplementary / detail split that collapses by its own measured width.
export {
  SplitView,
  SplitViewSidebar,
  SplitViewSupplementary,
  SplitViewDetail,
  SplitViewHeader,
  SplitViewContent,
  SplitViewToggle,
  SplitViewItem,
  SplitViewEmpty,
  useSplitView,
  useSplitViewColumn,
} from '@brett_lamy/ui';
export type {
  SplitViewColumn,
  SplitViewColumnProps,
  SplitViewEmptyProps,
  SplitViewHeaderProps,
  SplitViewItemProps,
  SplitViewProps,
  SplitViewSelection,
  SplitViewSidebarBehavior,
  SplitViewState,
  SplitViewToggleProps,
  SplitViewWidthClass,
} from '@brett_lamy/ui';
