// Generated by tools/registry/build.mjs from syntax-highlighting.json — do not edit.
// SyntaxHighlighting: Code highlighted on the GPU by gpu-lexer: file header, copy button, line numbers, highlighted and diff lines, inline code.
export {
  SyntaxHighlighting,
  SyntaxHighlightingHeader,
  SyntaxHighlightingTitle,
  SyntaxHighlightingCopyButton,
  SyntaxHighlightingContent,
  SyntaxTokens,
  syntaxHighlightingVariants,
  useSyntaxTokens,
  useSyntaxHighlighting,
  lexSyntax,
  webgpuSupported,
  languageFromPath,
  tokenizeLines,
} from '@brett_lamy/ui';
export type {
  SyntaxHighlighter,
  SyntaxHighlightingContentProps,
  SyntaxHighlightingCopyButtonProps,
  SyntaxHighlightingProps,
  SyntaxResult,
  SyntaxSpan,
  SyntaxToken,
  SyntaxTokenType,
  SyntaxTokensState,
} from '@brett_lamy/ui';
