// Generated by tools/registry/build.mjs from tab-view.json — do not edit.
// TabView: Tabs as parts: a bar at any edge, sliding indicator, directional panels, swipe between panels.
export {
  TabView,
  TabViewBar,
  TabViewList,
  TabViewTab,
  TabViewIndicator,
  TabViewSeparator,
  TabViewAction,
  TabViewHeader,
  TabViewFooter,
  TabViewPanels,
  TabViewPanel,
  useTabView,
  useTabViewTab,
} from '@brett_lamy/ui';
export type {
  TabViewActionProps,
  TabViewBarProps,
  TabViewBarVariant,
  TabViewIndicatorProps,
  TabViewOrientation,
  TabViewPlacement,
  TabViewProps,
  TabViewTabProps,
} from '@brett_lamy/ui';
