// Generated by tools/registry/build.mjs from theme.json — do not edit.
// Theme: BLProvider, ThemeScope and the appearance context: pick light/dark, a tint and a theme scope for a subtree. Colors are shadcn variables (see the bl-theme item for the iOS palette).
export {
  BLProvider,
  ThemeScope,
  AppearanceProvider,
  useAppearance,
  WorkbenchTheme,
  useWorkbenchAppearance,
  readThemeVars,
} from '@brett_lamy/ui';
export type {
  BLProviderProps,
  ThemeScopeName,
  ThemeScopeProps,
  ThemeScopeState,
  WorkbenchThemeProps,
} from '@brett_lamy/ui';
