// Generated by tools/registry/build.mjs from theme.json — do not edit.
// Theme: BLProvider and the appearance context: the iOS light/dark token palette every BL UI component reads.
export {
  BLProvider,
  AppearanceProvider,
  useAppearance,
  WorkbenchTheme,
  useWorkbenchAppearance,
  blLightVars,
  blDarkVars,
} from '@brett_lamy/ui';
export type { BLProviderProps, WorkbenchThemeProps } from '@brett_lamy/ui';
