/* Beautiful UI live blocks — ported from the prototype's window.__buiLIVE registry
   (project/beautiful.jsx), rebuilt on the @touchkit/beautiful public API. */
import {
  ApprovalCard, CodeBlockStream, ContextCards, DiffTable, FilterTable, FineTuneCard, InsightCards,
  RecommendationCard, RecordsTable, SearchPalette, SelectionActions, StreamingText, TaskRows, ToolChips,
  // pre-composed catalog demos (prototype-exact demo data)
  ThinkingDemo, SidebarDemo, ToastDemo, PlanReviewDemo, MemoryPillsDemo, AgentBoardDemo, CommandMenuDemo,
  PopoverDropdownDemo, CiteDemo, SkeletonDemo, LoadingStateDemo, DatePickerDemo, ComboboxDemo,
  ModelPickerDemo, KbdDemo,
} from '@touchkit/beautiful';
import type { LiveSpec } from './frame';

const imp = (name: string) =>
  'import { ' + name + ' } from "./beautiful.tsx"\n\nexport default function App() {\n  return <' + name + '/>\n}';

const wrap = (w: number, node: React.ReactNode) => <div style={{ maxWidth: w, margin: '0 auto' }}>{node}</div>;

export const LIVE_BUI: Record<string, LiveSpec> = {
  buiLoading: { title: 'LoadingState', theme: 'wb', h: 280,
    code: 'import { LoadingState } from "./beautiful.tsx"\n\nexport default function App() {\n  return <LoadingState variant="grid" label="Churning"/>\n  // variants: "grid" | "dots" | "orbit"\n}',
    Render: () => <LoadingStateDemo /> },
  buiThinking: { title: 'Thinking', theme: 'wb', h: 340,
    code: 'import { Thinking } from "./beautiful.tsx"\n\nexport default function App() {\n  return (\n    <Thinking defaultOpen>\n      <Thinking.Trigger>Thinking</Thinking.Trigger>\n      <Thinking.Content>\n        <Thinking.Tabs>\n          <Thinking.Tab id="steps">Steps</Thinking.Tab>\n          <Thinking.Tab id="search">Search</Thinking.Tab>\n          <Thinking.Tab id="coding">Coding</Thinking.Tab>\n        </Thinking.Tabs>\n        <Thinking.Panel id="steps">\n          <Thinking.Step done>Pull supplier lead times</Thinking.Step>\n          <Thinking.Step>Draft the reorder plan</Thinking.Step>\n        </Thinking.Panel>\n        <Thinking.Panel id="search">\n          <Thinking.Search site="scoopdata.io">seasonal cone demand</Thinking.Search>\n        </Thinking.Panel>\n        <Thinking.Panel id="coding">\n          <Thinking.Code>{"const risk = score(skus)"}</Thinking.Code>\n        </Thinking.Panel>\n      </Thinking.Content>\n    </Thinking>\n  )\n}',
    Render: () => wrap(520, <ThinkingDemo />) },
  buiStreaming: { title: 'StreamingText', theme: 'wb', h: 360, code: imp('StreamingText'),
    Render: () => wrap(520, <StreamingText />) },
  buiApproval: { title: 'ApprovalCard', theme: 'wb', h: 290,
    code: 'import { ApprovalCard } from "./beautiful.tsx"\n\nexport default function App() {\n  return <ApprovalCard\n    question="How many flavors should we launch?"\n    options={["Three (core line)", "Five (full case)", "Just one hero"]}\n    onPick={console.log}/>\n}',
    Render: () => wrap(420, <ApprovalCard question="How many flavors should we launch?" options={['Three (core line)', 'Five (full case)', 'Just one hero']} />) },
  buiChips: { title: 'ToolChips', theme: 'wb', h: 250, code: imp('ToolChips'),
    Render: () => wrap(520, <ToolChips />) },
  buiTasks: { title: 'TaskRows', theme: 'wb', h: 430, code: imp('TaskRows'),
    Render: () => wrap(520, <TaskRows />) },
  buiRecommend: { title: 'RecommendationCard', theme: 'wb', h: 300, code: imp('RecommendationCard'),
    Render: () => wrap(440, <RecommendationCard />) },
  buiContext: { title: 'ContextCards', theme: 'wb', h: 360, code: imp('ContextCards'),
    Render: () => wrap(520, <ContextCards />) },
  buiDiff: { title: 'DiffTable', theme: 'wb', h: 330, code: imp('DiffTable'),
    Render: () => wrap(520, <DiffTable />) },
  buiRecords: { title: 'RecordsTable', theme: 'wb', h: 400, code: imp('RecordsTable'),
    Render: () => wrap(560, <RecordsTable />) },
  buiFilter: { title: 'FilterTable', theme: 'wb', h: 380, code: imp('FilterTable'),
    Render: () => wrap(540, <FilterTable />) },
  buiSidebar: { title: 'Sidebar system', theme: 'wb', h: 480,
    code: 'import { SidebarProvider, Sidebar, SidebarTrigger, SidebarInset } from "./beautiful.tsx"\n\nexport default function App() {\n  return (\n    <SidebarProvider defaultOpen breakpoint={560}>\n      <Sidebar variant="rail">  {/* docked | rail | float | overlay */}\n        <Sidebar.Header>\n          <Sidebar.Workspace name="Creamery Ops" detail="Production"/>\n        </Sidebar.Header>\n        <Sidebar.Content>\n          <Sidebar.Search/>\n          <Sidebar.Section title="Workspace">\n            <Sidebar.Item icon="home" label="Home" active/>\n            <Sidebar.Item icon="bolt" label="Agent tasks" badge={4}/>\n            <Sidebar.Item icon="inbox" label="Inbox"/>\n          </Sidebar.Section>\n        </Sidebar.Content>\n      </Sidebar>\n      <SidebarInset>\n        <SidebarTrigger/>  {/* hamburger — toggles any variant */}\n        …main content…\n      </SidebarInset>\n    </SidebarProvider>\n  )\n}',
    Render: () => <SidebarDemo /> },
  buiSearch: { title: 'SearchPalette', theme: 'wb', h: 320, code: imp('SearchPalette'),
    Render: () => wrap(420, <SearchPalette />) },
  buiInsights: { title: 'InsightCards', theme: 'wb', h: 340, code: imp('InsightCards'),
    Render: () => wrap(420, <InsightCards />) },
  buiCode: { title: 'CodeBlockStream', theme: 'wb', h: 360, code: imp('CodeBlockStream'),
    Render: () => wrap(520, <CodeBlockStream />) },
  buiFinetune: { title: 'FineTuneCard', theme: 'wb', h: 290, code: imp('FineTuneCard'),
    Render: () => <div style={{ display: 'grid', justifyContent: 'center' }}><FineTuneCard /></div> },
  buiSelection: { title: 'SelectionActions', theme: 'wb', h: 250, code: imp('SelectionActions'),
    Render: () => wrap(480, <SelectionActions />) },
  buiToast: { title: 'Toast', theme: 'wb', h: 380,
    code: 'import { ToastProvider, useToast } from "./beautiful.tsx"\n\nfunction Panel() {\n  const toast = useToast()\n  return <button onClick={() => toast.push({\n    tone: "success", title: "Order placed",\n    detail: "48 cases of waffle cones from cone_king.",\n  })}>Place order</button>\n}\n\nexport default function App() {\n  return <ToastProvider><Panel/></ToastProvider>\n}',
    Render: () => <ToastDemo /> },
  buiCitation: { title: 'Cite', theme: 'wb', h: 280,
    code: 'import { Cite } from "./beautiful.tsx"\n\nexport default function App() {\n  return (\n    <p>\n      Pistachio is up 18% quarter over quarter\n      <Cite n={1}>\n        <Cite.Quote>Q4 velocity: pistachio +18%, vanilla +6%…</Cite.Quote>\n        <Cite.Source kind="CSV">Sales Velocity Export.csv</Cite.Source>\n      </Cite>\n      , with the sharpest lift on weekends.\n    </p>\n  )\n}',
    Render: () => <CiteDemo /> },
  buiPlan: { title: 'PlanReview', theme: 'wb', h: 400,
    code: 'import { PlanReview } from "./beautiful.tsx"\n\nexport default function App() {\n  const [steps, setSteps] = React.useState(initialSteps)\n  const [ok, setOk] = React.useState(false)\n  return (\n    <PlanReview approved={ok} onApprove={() => setOk(true)}>\n      {steps.map((s, i) => (\n        <PlanReview.Step key={s.id} n={i + 1} detail={s.detail}\n          onUp={i > 0 ? () => move(i, -1) : null}\n          onDown={i < steps.length - 1 ? () => move(i, 1) : null}\n          onRemove={() => setSteps(x => x.filter(y => y !== s))}>\n          {s.title}\n        </PlanReview.Step>\n      ))}\n    </PlanReview>\n  )\n}',
    Render: () => <PlanReviewDemo /> },
  buiMemory: { title: 'MemoryPills', theme: 'wb', h: 250,
    code: 'import { MemoryPills } from "./beautiful.tsx"\n\nexport default function App() {\n  const [pills, setPills] = React.useState(facts)\n  return (\n    <MemoryPills label="Agent context">\n      {pills.map(p => (\n        <MemoryPills.Pill key={p.id} icon={p.icon}\n          onDismiss={() => setPills(x => x.filter(y => y !== p))}>\n          {p.text}\n        </MemoryPills.Pill>\n      ))}\n    </MemoryPills>\n  )\n}',
    Render: () => <MemoryPillsDemo /> },
  buiAgents: { title: 'AgentBoard', theme: 'wb', h: 330,
    code: 'import { AgentBoard } from "./beautiful.tsx"\n\nexport default function App() {\n  return (\n    <AgentBoard>\n      <AgentBoard.Agent name="Researcher" task="Scanning supplier catalogs" state="running" progress={0.4}/>\n      <AgentBoard.Agent name="Analyst" task="Scoring stockout risk" state="running"/>\n      <AgentBoard.Agent name="Writer" task="Drafted 2 supplier emails" state="done"/>\n      <AgentBoard.Agent name="Checker" task="Cold-chain cert lookup failed" state="failed"/>\n    </AgentBoard>\n  )\n}',
    Render: () => <AgentBoardDemo /> },
  buiCommand: { title: 'CommandMenu', theme: 'wb', h: 400,
    code: 'import { CommandMenu, Kbd } from "./beautiful.tsx"\n\nexport default function App() {\n  const [open, setOpen] = React.useState(false)\n  return (\n    <div style={{ position: "relative", height: 320 }}>\n      <button onClick={() => setOpen(true)}>Open <Kbd>⌘K</Kbd></button>\n      <CommandMenu open={open} onClose={() => setOpen(false)}>\n        <CommandMenu.Input/>\n        <CommandMenu.List>\n          <CommandMenu.Group title="Agent">\n            <CommandMenu.Item icon="bolt" kbd="⌘R" keywords="forecast">Run demand forecast</CommandMenu.Item>\n            <CommandMenu.Item icon="doc" keywords="email draft">Draft supplier email</CommandMenu.Item>\n          </CommandMenu.Group>\n          <CommandMenu.Group title="Navigate">\n            <CommandMenu.Item icon="home" kbd="G H">Go home</CommandMenu.Item>\n          </CommandMenu.Group>\n        </CommandMenu.List>\n      </CommandMenu>\n    </div>\n  )\n}',
    Render: () => <CommandMenuDemo /> },
  buiPopover: { title: 'Popover · Dropdown', theme: 'wb', h: 320,
    code: 'import { Popover, Dropdown } from "./beautiful.tsx"\n\nexport default function App() {\n  return (\n    <div style={{ display: "flex", gap: 16 }}>\n      <Popover>\n        <Popover.Trigger><button>Details</button></Popover.Trigger>\n        <Popover.Content>Any content — the trigger clones\n          its child (asChild style).</Popover.Content>\n      </Popover>\n      <Dropdown>\n        <Dropdown.Trigger><button>Actions</button></Dropdown.Trigger>\n        <Dropdown.Menu>\n          <Dropdown.Item icon="pen" kbd="⌘E">Edit</Dropdown.Item>\n          <Dropdown.Item icon="copy">Duplicate</Dropdown.Item>\n          <Dropdown.Separator/>\n          <Dropdown.Item icon="trash" danger>Delete</Dropdown.Item>\n        </Dropdown.Menu>\n      </Dropdown>\n    </div>\n  )\n}',
    Render: () => <PopoverDropdownDemo /> },
  buiSkeleton: { title: 'Skeleton', theme: 'wb', h: 360,
    code: 'import { Skeleton } from "./beautiful.tsx"\n\nexport default function App() {\n  const [loading, setLoading] = React.useState(true)\n  return (\n    <Skeleton loading={loading}>\n      {/* any subtree — the skeleton is generated from its rendered layout */}\n      <SupplierCard/>\n    </Skeleton>\n  )\n}',
    Render: () => <SkeletonDemo /> },
  buiDate: { title: 'DatePicker', theme: 'wb', h: 390,
    code: 'import { DatePicker } from "./beautiful.tsx"\n\nexport default function App() {\n  const [date, setDate] = React.useState(null)\n  return <DatePicker value={date} onChange={setDate}/>\n}',
    Render: () => <DatePickerDemo /> },
  buiCombobox: { title: 'Combobox', theme: 'wb', h: 330,
    code: 'import { Combobox } from "./beautiful.tsx"\n\nexport default function App() {\n  const [supplier, setSupplier] = React.useState(null)\n  return <Combobox value={supplier} onChange={setSupplier}\n    placeholder="Pick a supplier…"\n    options={["Aurora Scoops", "Kumo Creamery", "Maple Orbit",\n      "Coral Coast Sorbet", "Ember Cone Company"]}/>\n}',
    Render: () => <ComboboxDemo /> },
  buiModelPicker: { title: 'ModelPicker', theme: 'wb', h: 440,
    code: 'import { ModelPicker } from "./beautiful.tsx"\n\nconst MODELS = [\n  { id: "pickle", name: "Big Pickle", provider: "opencode", source: "OpenCode · opencode" },\n  { id: "dr-max", name: "Deep Research Max Preview", provider: "google", source: "OpenCode · google" },\n  { id: "sonnet", name: "Claude Sonnet 4.5", provider: "anthropic", source: "OpenCode · anthropic" },\n  …\n]\n\nexport default function App() {\n  const [model, setModel] = React.useState("pickle")\n  return <ModelPicker models={MODELS} value={model}\n    onChange={setModel} favorites={["sonnet"]}/>\n}',
    Render: () => <ModelPickerDemo /> },
  buiKbd: { title: 'Kbd', theme: 'wb', h: 280,
    code: 'import { Kbd } from "./beautiful.tsx"\n\nexport default function App() {\n  return <p>Press <Kbd>⌘K</Kbd> to search, <Kbd>esc</Kbd> to close.</p>\n}',
    Render: () => <KbdDemo /> },
};
