#!/usr/bin/env node
/* Generates everything derived from the token list in packages/ui/src/tokens.css (`@theme inline`).
 *
 *   node tools/tokens/build.mjs           → packages/ui/src/lib/tokens.generated.ts
 *   node tools/tokens/build.mjs --check   → exit 1 if the committed file is stale (CI)
 *
 * tokens.css is the single source of truth: the user defines CSS variables (`--primary`, `--radius`, …), tokens.css
 * maps them to Tailwind theme variables (`--color-primary: var(--primary)`, `--radius-xl: calc(var(--radius) * 1.2)`),
 * and this script turns the same list into what TypeScript needs: the typed variable names for `ThemeScope`'s `vars`,
 * the list a portalled overlay copies, and the tailwind-merge theme (so `cn('text-footnote text-foreground')` keeps
 * both — one is a size, the other a color).
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const CSS = join(ROOT, 'packages/ui/src/tokens.css');
const OUT = join(ROOT, 'packages/ui/src/lib/tokens.generated.ts');
const check = process.argv.includes('--check');

const css = readFileSync(CSS, 'utf8');
// Every `@theme` block (inline or not): declarations `--name: value;`.
const decls = [];
for (const block of css.matchAll(/@theme(?:\s+inline)?\s*\{([\s\S]*?)\n\}/g)) {
  const body = block[1].replace(/\/\*[\s\S]*?\*\//g, '');
  for (const m of body.matchAll(/^\s*--([\w-]+):\s*([^;]+);/gm)) decls.push([m[1], m[2].trim()]);
}

const group = (prefix) =>
  decls
    .filter(([n]) => n.startsWith(prefix + '-') && !n.includes('--'))
    .map(([n, v]) => [n.slice(prefix.length + 1), v]);

const colors = group('color');
const texts = group('text').map(([n]) => n);
const radii = group('radius').map(([n]) => n);
const shadows = group('shadow').map(([n]) => n);
const spacings = group('spacing').map(([n]) => n);
const fonts = group('font').map(([n]) => n);

// The variable a color utility reads: the first `var(--x` in its value (`--color-success: var(--success, …)` → success).
const varOf = (value) => value.match(/var\(--([\w-]+)/)?.[1];
const colorVars = colors.map(([n, v]) => varOf(v) ?? n);
// Non-color variables a scope may set. `radius` is the base the whole radius scale derives from.
const otherVars = ['radius', 'font-sans', 'font-mono'];

const list = (name, items) => `export const ${name} = [\n${items.map((i) => `  '${i}',`).join('\n')}\n] as const;\n`;

const out =
  `// Generated by tools/tokens/build.mjs from tokens.css — do not edit.\n` +
  `// The token list (tokens.css \`@theme inline\`) is the source; edit it there and run \`node tools/tokens/build.mjs\`.\n\n` +
  `/** Color utilities (bg-*, text-*, border-*…) by name: \`--color-<name>\`. */\n` +
  list('COLOR_TOKENS', colors.map(([n]) => n)) +
  `\n/** Font-size utilities (text-*): \`--text-<name>\`. Size only — no line-height. */\n` +
  list('TEXT_TOKENS', texts) +
  `\n/** Radius utilities (rounded-*): \`--radius-<name>\`, all derived from the \`--radius\` variable. */\n` +
  list('RADIUS_TOKENS', radii) +
  `\n/** Shadow utilities (shadow-*): \`--shadow-<name>\`. */\n` +
  list('SHADOW_TOKENS', shadows) +
  `\n/** Spacing utilities (h-*, min-h-*, size-*…) added by BL UI: \`--spacing-<name>\`. */\n` +
  list('SPACING_TOKENS', spacings) +
  `\n/** Font-family utilities (font-*): \`--font-<name>\`. */\n` +
  list('FONT_TOKENS', fonts) +
  `\n/** The CSS variables a theme (or a \`ThemeScope\`'s \`vars\`) sets, without the leading \`--\`. */\n` +
  list('THEME_VARS', [...new Set([...colorVars, ...otherVars])]) +
  `\nexport type ThemeVar = (typeof THEME_VARS)[number];\n`;

if (check) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (cur !== out) {
    console.error('packages/ui/src/lib/tokens.generated.ts is stale — run `node tools/tokens/build.mjs`');
    process.exit(1);
  }
  console.log('tokens: up to date');
} else {
  writeFileSync(OUT, out);
  console.log(`tokens: ${colors.length} colors, ${texts.length} text, ${radii.length} radius, ${shadows.length} shadow, ${spacings.length} spacing, ${fonts.length} font → lib/tokens.generated.ts`);
}
