import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const errs = []; p.on('pageerror', (e) => errs.push(String(e))); p.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
await p.goto('http://localhost:4417/');
await p.waitForTimeout(1000);
await p.click('[data-page="composer"]');
await p.waitForTimeout(2000);
const pm = p.locator('[data-slot=composer] .ProseMirror').first();
await pm.scrollIntoViewIfNeeded();
await pm.click();
await p.evaluate(async () => {
  const c = document.createElement('canvas'); c.width = 800; c.height = 400;
  const x = c.getContext('2d'); x.fillStyle = '#e8eefc'; x.fillRect(0, 0, 800, 400); x.fillStyle = '#123'; x.font = '48px sans-serif'; x.fillText('Screenshot', 260, 210);
  const blob = await new Promise((r) => c.toBlob(r, 'image/png'));
  const dt = new DataTransfer(); dt.items.add(new File([blob], 'image.png', { type: 'image/png' }));
  const ev = new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true });
  document.querySelector('[data-slot=composer] .ProseMirror').dispatchEvent(ev);
});
await p.waitForTimeout(800);
await p.click('[title="Annotate with PencilKit"]');
await p.waitForTimeout(800);
const box = await p.locator('[data-slot=annotate-lightbox] [data-slot=pencil-canvas]').boundingBox();
console.log('canvas', box);
await p.mouse.move(box.x + 100, box.y + 100); await p.mouse.down();
for (let i = 0; i < 20; i++) await p.mouse.move(box.x + 100 + i * 15, box.y + 100 + Math.sin(i / 3) * 40);
await p.mouse.up();
await p.waitForTimeout(300);
await p.screenshot({ path: '/tmp/anno-open.png' }); console.log(await p.evaluate(() => { const o = document.querySelector('[data-slot=annotate-lightbox]'); const cs = getComputedStyle(o); return [o.parentElement.tagName, o.parentElement.getAttribute('data-slot'), cs.backgroundColor, cs.opacity, cs.zIndex, cs.position]; }));
await p.getByRole('button', { name: 'Save annotation' }).click();
await p.waitForTimeout(800);
const src = await p.locator('[data-slot=composer] img[alt="pasted attachment"]').getAttribute('src');
console.log('saved len', src.length, 'errors', errs.slice(0, 5));
await p.locator('[data-slot=composer]').first().screenshot({ path: '/tmp/anno-after.png' });
await b.close();
