#!/usr/bin/env node
/* Regenerates the Google Fonts catalog the FontPicker offers, from the metadata fonts.google.com itself reads.
 *
 *   node tools/google-fonts/catalog.mjs   → packages/ui/src/lib/google-fonts.generated.ts
 *
 * The most popular families that cover Latin (CJK families, whose files are huge, and Noto's families for other
 * scripts are left out), topped up so each category has its most popular few, each as [family, category, weights,
 * italics]: weights is `min..max` for a variable font, else its static weights.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const OUT = join(ROOT, 'packages/ui/src/lib/google-fonts.generated.ts');
const COUNT = 300;
const PER_CATEGORY = 30;
const CATEGORIES = ['Sans Serif', 'Serif', 'Display', 'Handwriting', 'Monospace'];
const CJK = new Set(['Jpan', 'Hans', 'Hant', 'Hani', 'Kore']);

const res = await fetch('https://fonts.google.com/metadata/fonts');
if (!res.ok) throw new Error(`fonts.google.com/metadata/fonts: ${res.status}`);
const { familyMetadataList: all } = await res.json();

const latin = all
  .filter((f) => f.subsets.includes('latin') && !CJK.has(f.primaryScript) && !(f.isNoto && f.primaryScript) && CATEGORIES.includes(f.category))
  .sort((a, b) => a.popularity - b.popularity || a.family.localeCompare(b.family));
// The most popular overall, topped up so every category has a few to choose from.
const picked = new Set(latin.slice(0, COUNT));
for (const c of CATEGORIES) for (const f of latin.filter((x) => x.category === c).slice(0, PER_CATEGORY)) picked.add(f);
const rows = latin.filter((f) => picked.has(f)).map((f) => {
  const keys = Object.keys(f.fonts);
  const wght = f.axes.find((a) => a.tag === 'wght');
  const weights = wght
    ? `${Math.max(100, wght.min)}..${Math.min(900, wght.max)}`
    : [...new Set(keys.map((k) => Number.parseInt(k, 10)))].filter((w) => w >= 100 && w <= 900).sort((a, b) => a - b).join(',');
  return [f.family, CATEGORIES.indexOf(f.category), weights, keys.some((k) => k.endsWith('i')) ? 1 : 0];
});

const q = (v) => `'${String(v).replace(/'/g, "\\'")}'`;
const lines = rows.map(([family, cat, weights, italic]) => `  [${q(family)}, ${cat}, ${q(weights)}, ${italic}],`);
writeFileSync(OUT, `/* Generated by tools/google-fonts/catalog.mjs from fonts.google.com's metadata. Do not edit.
   The most popular Google Fonts families that cover Latin (and the ${PER_CATEGORY} most popular of each category), most
   popular first:
   [family, category (an index into FONT_CATEGORIES), weights ('min..max' variable, else the static ones), italics]. */
export const GOOGLE_FONT_ROWS: readonly (readonly [string, number, string, number])[] = [
${lines.join('\n')}
];
`);
const counts = CATEGORIES.map((c, i) => `${c} ${rows.filter((r) => r[1] === i).length}`).join(', ');
console.log(`google-fonts: ${rows.length} families (${counts}) → ${OUT}`);
